spring.application.name=distributed-rate-limiter
server.port=8081

spring.data.redis.host=localhost
spring.data.redis.port=6379

rate.limit.max-requests=5
rate.limit.window-seconds=10

rate.limit.bucket-capacity=5
rate.limit.refill-rate=1

#rate.limit.algorithm=sliding-window
rate.limit.algorithm=token-bucket